name: Maven CI with Semgrep Supply Chain

on: 
  workflow_dispatch:
  pull_request: {}
  push:
    branches:
    - main
    paths:
    - .github/workflows/main.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven and Install Dependencies
        run: mvn dependency:tree -DoutputFile=maven_dep_tree.txt -DskipTests
      - name: Upload Dependency Tree Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mavendeptree
          path: maven_dep_tree.txt

  semgrep_scan:
    needs: build
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact from previous job
        uses: actions/download-artifact@v4
        with:
          name: mavendeptree

      - name: Debug Semgrep Environment
        run: ls -la

      - name: Validate Semgrep Token
        run: echo $SEMGREP_APP_TOKEN | wc -c

      - name: Run Semgrep with Explicit File Path
        run: semgrep supply-chain scan --config p/supply-chain --json --dependency-tree /tmp/maven_dep_tree.txt > /tmp/semgrep_results.json


 
       
