name: Maven CI with Nexus IQ

on: 
  [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean package 

  scan:
     name: semgrep/ci
     runs-on: ubuntu-latest
     needs: build

     steps: 
     - name: Checkout repository
       uses: actions/checkout@v1

     - name: Download Artifact
       uses: actions/download-artifact@v1
       with:
         name: bad-java-app
         path: target

     - name: Semgrep Scan
       container:
      # A Docker image with Semgrep installed. Do not change this.
        image: semgrep/semgrep
  if: (github.actor != 'dependabot[bot]')

    steps:
      # Fetch project source with GitHub Actions Checkout. Use either v3 or v4.
      - uses: actions/checkout@v4
      # Run the "semgrep ci" command on the command line of the docker image.
      - run: semgrep ci
        env:
          # Connect to Semgrep AppSec Platform through your SEMGREP_APP_TOKEN.
          # Generate a token from Semgrep AppSec Platform > Settings
          # and add it to your GitHub secrets.
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

